"""add_regional_factors_and_ai_verdict_fields

Revision ID: 135bec871877
Revises: 
Create Date: 2026-01-14 09:55:18.655123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '135bec871877'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regional_factors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('region_code', sa.String(length=10), nullable=True),
    sa.Column('region_name', sa.String(length=100), nullable=True),
    sa.Column('grid_ef_kwh', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('grid_ef_source', sa.String(length=100), nullable=True),
    sa.Column('grid_ef_year', sa.String(length=4), nullable=True),
    sa.Column('regulations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('incentives', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('carbon_price_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('carbon_pricing_scheme', sa.String(length=100), nullable=True),
    sa.Column('archetype_benchmarks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regional_factors_country_code'), 'regional_factors', ['country_code'], unique=False)
    op.create_index(op.f('ix_regional_factors_region_code'), 'regional_factors', ['region_code'], unique=False)
    op.drop_constraint('activity_baselines_organization_id_activity_type_month_key', 'activity_baselines', type_='unique')
    op.create_unique_constraint('uq_baseline_org_type_month', 'activity_baselines', ['organization_id', 'activity_type', 'month'])
    op.create_index(op.f('ix_emission_activities_content_hash'), 'emission_activities', ['content_hash'], unique=False)
    op.add_column('flagged_events', sa.Column('ai_verdict', sa.String(length=1), nullable=True))
    op.add_column('flagged_events', sa.Column('ai_verdict_explanation', sa.Text(), nullable=True))
    op.add_column('flagged_events', sa.Column('required_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('flagged_events', sa.Column('co2e_90d_estimate', sa.Numeric(precision=20, scale=6), nullable=True))
    op.add_column('flagged_events', sa.Column('ai_confidence', sa.String(length=1), nullable=True))
    op.add_column('flagged_events', sa.Column('immediate_action', sa.Text(), nullable=True))
    op.add_column('flagged_events', sa.Column('next_action', sa.Text(), nullable=True))
    op.drop_index('idx_strategy_org', table_name='reduction_strategies')
    op.drop_index('idx_strategy_target', table_name='reduction_strategies')
    op.drop_index('idx_suppression_org', table_name='suppression_rules')
    op.create_index(op.f('ix_suppression_rules_organization_id'), 'suppression_rules', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suppression_rules_organization_id'), table_name='suppression_rules')
    op.create_index('idx_suppression_org', 'suppression_rules', ['organization_id'], unique=False)
    op.create_index('idx_strategy_target', 'reduction_strategies', ['target_id'], unique=False)
    op.create_index('idx_strategy_org', 'reduction_strategies', ['organization_id'], unique=False)
    op.drop_column('flagged_events', 'next_action')
    op.drop_column('flagged_events', 'immediate_action')
    op.drop_column('flagged_events', 'ai_confidence')
    op.drop_column('flagged_events', 'co2e_90d_estimate')
    op.drop_column('flagged_events', 'required_evidence')
    op.drop_column('flagged_events', 'ai_verdict_explanation')
    op.drop_column('flagged_events', 'ai_verdict')
    op.drop_index(op.f('ix_emission_activities_content_hash'), table_name='emission_activities')
    op.drop_constraint('uq_baseline_org_type_month', 'activity_baselines', type_='unique')
    op.create_unique_constraint('activity_baselines_organization_id_activity_type_month_key', 'activity_baselines', ['organization_id', 'activity_type', 'month'])
    op.drop_index(op.f('ix_regional_factors_region_code'), table_name='regional_factors')
    op.drop_index(op.f('ix_regional_factors_country_code'), table_name='regional_factors')
    op.drop_table('regional_factors')
    # ### end Alembic commands ###
