"""initial_schema

Revision ID: abd6d9b7f406
Revises: 
Create Date: 2026-07-06 17:08:53.156594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd6d9b7f406'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('emission_archetype', sa.String(length=50), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_baselines',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('organization_id', sa.String(36), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('p10', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('p50', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('p90', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('last_calculated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'activity_type', 'month', name='uq_baseline_org_type_month')
    )
    op.create_index(op.f('ix_activity_baselines_activity_type'), 'activity_baselines', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activity_baselines_organization_id'), 'activity_baselines', ['organization_id'], unique=False)
    op.create_table('copilot_cache',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('query_hash', sa.String(length=64), nullable=False),
    sa.Column('query_type', sa.String(length=50), nullable=False),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cache_expires', 'copilot_cache', ['expires_at'], unique=False)
    op.create_index('idx_cache_org_type', 'copilot_cache', ['organization_id', 'query_type'], unique=False)
    op.create_index(op.f('ix_copilot_cache_query_hash'), 'copilot_cache', ['query_hash'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reporting_year', sa.String(length=4), nullable=False),
    sa.Column('organization_id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_reporting_year'), 'projects', ['reporting_year'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('organization_id', sa.String(36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('batch_jobs',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('processed_records', sa.Integer(), nullable=True),
    sa.Column('successful_records', sa.Integer(), nullable=True),
    sa.Column('failed_records', sa.Integer(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('project_id', sa.String(36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_jobs_celery_task_id'), 'batch_jobs', ['celery_task_id'], unique=True)
    op.create_index(op.f('ix_batch_jobs_status'), 'batch_jobs', ['status'], unique=False)
    op.create_table('custom_mappings',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('internal_label', sa.String(length=255), nullable=False),
    sa.Column('internal_code', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('climatiq_activity_id', sa.String(length=255), nullable=False),
    sa.Column('climatiq_region', sa.String(length=10), nullable=True),
    sa.Column('climatiq_year', sa.String(length=4), nullable=True),
    sa.Column('climatiq_source', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('mapping_method', sa.String(length=50), nullable=False),
    sa.Column('default_parameters', sa.Text(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('organization_id', sa.String(36), nullable=False),
    sa.Column('created_by', sa.String(36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'internal_label', name='uix_org_internal_label')
    )
    op.create_table('reduction_targets',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('organization_id', sa.String(36), nullable=False),
    sa.Column('project_id', sa.String(36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=True),
    sa.Column('baseline_year', sa.String(length=4), nullable=False),
    sa.Column('baseline_value', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('target_year', sa.String(length=4), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('milestones', sa.Text(), nullable=True),
    sa.Column('current_year', sa.String(length=4), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('current_reduction_pct', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('progress_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_target_org_scope', 'reduction_targets', ['organization_id', 'scope'], unique=False)
    op.create_index('idx_target_org_status', 'reduction_targets', ['organization_id', 'status'], unique=False)
    op.create_table('suppression_rules',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('organization_id', sa.String(36), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('scope', sa.String(length=50), nullable=True),
    sa.Column('project_id', sa.String(36), nullable=True),
    sa.Column('confidence_weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('requires_revalidation', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_revalidated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppression_rules_organization_id'), 'suppression_rules', ['organization_id'], unique=False)
    op.create_table('emission_activities',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('sub_type', sa.String(length=50), nullable=True),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('activity_date', sa.DateTime(), nullable=False),
    sa.Column('co2e_kg', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('co2e_unit', sa.String(length=10), nullable=True),
    sa.Column('calculation_method', sa.String(length=20), nullable=True),
    sa.Column('constituent_gases', sa.Text(), nullable=True),
    sa.Column('input_data', sa.Text(), nullable=False),
    sa.Column('emission_factor_id', sa.String(length=255), nullable=True),
    sa.Column('source_dataset', sa.String(length=100), nullable=True),
    sa.Column('data_version', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=10), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('project_id', sa.String(36), nullable=False),
    sa.Column('batch_job_id', sa.String(36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_job_id'], ['batch_jobs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_project_date', 'emission_activities', ['project_id', 'activity_date'], unique=False)
    op.create_index('idx_activity_scope_type', 'emission_activities', ['scope', 'activity_type'], unique=False)
    op.create_index('idx_input_data_gin', 'emission_activities', ['input_data'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_emission_activities_activity_date'), 'emission_activities', ['activity_date'], unique=False)
    op.create_index(op.f('ix_emission_activities_activity_type'), 'emission_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_emission_activities_content_hash'), 'emission_activities', ['content_hash'], unique=True)
    op.create_index(op.f('ix_emission_activities_emission_factor_id'), 'emission_activities', ['emission_factor_id'], unique=False)
    op.create_index(op.f('ix_emission_activities_scope'), 'emission_activities', ['scope'], unique=False)
    op.create_table('reduction_strategies',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('organization_id', sa.String(36), nullable=False),
    sa.Column('target_id', sa.String(36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=True),
    sa.Column('archetype', sa.String(length=50), nullable=True),
    sa.Column('estimated_reduction_kg', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('estimated_reduction_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('estimated_savings', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('payback_period_months', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('implementation_timeframe', sa.String(length=50), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['reduction_targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_strategy_archetype', 'reduction_strategies', ['organization_id', 'archetype'], unique=False)
    op.create_index('idx_strategy_cache', 'reduction_strategies', ['prompt_hash', 'expires_at'], unique=False)
    op.create_index('idx_strategy_org_target', 'reduction_strategies', ['organization_id', 'target_id'], unique=False)
    op.create_index(op.f('ix_reduction_strategies_prompt_hash'), 'reduction_strategies', ['prompt_hash'], unique=False)
    op.create_table('flagged_events',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('organization_id', sa.String(36), nullable=False),
    sa.Column('project_id', sa.String(36), nullable=True),
    sa.Column('activity_id', sa.String(36), nullable=True),
    sa.Column('flag_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolved_by', sa.String(36), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('confidence_breakdown', sa.Text(), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('ai_explanation_model', sa.String(length=50), nullable=True),
    sa.Column('ai_explanation_at', sa.DateTime(), nullable=True),
    sa.Column('ai_verdict', sa.String(length=1), nullable=True),
    sa.Column('ai_verdict_explanation', sa.Text(), nullable=True),
    sa.Column('required_evidence', sa.Text(), nullable=True),
    sa.Column('co2e_90d_estimate', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('ai_confidence', sa.String(length=1), nullable=True),
    sa.Column('immediate_action', sa.Text(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('audit_run_id', sa.String(36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['emission_activities.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_flagged_audit_run', 'flagged_events', ['audit_run_id'], unique=False)
    op.create_index('idx_flagged_org_status', 'flagged_events', ['organization_id', 'status'], unique=False)
    op.create_index('idx_flagged_org_type', 'flagged_events', ['organization_id', 'flag_type'], unique=False)
    op.create_index(op.f('ix_flagged_events_flag_type'), 'flagged_events', ['flag_type'], unique=False)
    op.create_index(op.f('ix_flagged_events_severity'), 'flagged_events', ['severity'], unique=False)
    op.create_index(op.f('ix_flagged_events_status'), 'flagged_events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flagged_events_status'), table_name='flagged_events')
    op.drop_index(op.f('ix_flagged_events_severity'), table_name='flagged_events')
    op.drop_index(op.f('ix_flagged_events_flag_type'), table_name='flagged_events')
    op.drop_index('idx_flagged_org_type', table_name='flagged_events')
    op.drop_index('idx_flagged_org_status', table_name='flagged_events')
    op.drop_index('idx_flagged_audit_run', table_name='flagged_events')
    op.drop_table('flagged_events')
    op.drop_index(op.f('ix_reduction_strategies_prompt_hash'), table_name='reduction_strategies')
    op.drop_index('idx_strategy_org_target', table_name='reduction_strategies')
    op.drop_index('idx_strategy_cache', table_name='reduction_strategies')
    op.drop_index('idx_strategy_archetype', table_name='reduction_strategies')
    op.drop_table('reduction_strategies')
    op.drop_index(op.f('ix_emission_activities_scope'), table_name='emission_activities')
    op.drop_index(op.f('ix_emission_activities_emission_factor_id'), table_name='emission_activities')
    op.drop_index(op.f('ix_emission_activities_content_hash'), table_name='emission_activities')
    op.drop_index(op.f('ix_emission_activities_activity_type'), table_name='emission_activities')
    op.drop_index(op.f('ix_emission_activities_activity_date'), table_name='emission_activities')
    op.drop_index('idx_input_data_gin', table_name='emission_activities', postgresql_using='gin')
    op.drop_index('idx_activity_scope_type', table_name='emission_activities')
    op.drop_index('idx_activity_project_date', table_name='emission_activities')
    op.drop_table('emission_activities')
    op.drop_index(op.f('ix_suppression_rules_organization_id'), table_name='suppression_rules')
    op.drop_table('suppression_rules')
    op.drop_index('idx_target_org_status', table_name='reduction_targets')
    op.drop_index('idx_target_org_scope', table_name='reduction_targets')
    op.drop_table('reduction_targets')
    op.drop_table('custom_mappings')
    op.drop_index(op.f('ix_batch_jobs_status'), table_name='batch_jobs')
    op.drop_index(op.f('ix_batch_jobs_celery_task_id'), table_name='batch_jobs')
    op.drop_table('batch_jobs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_reporting_year'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_copilot_cache_query_hash'), table_name='copilot_cache')
    op.drop_index('idx_cache_org_type', table_name='copilot_cache')
    op.drop_index('idx_cache_expires', table_name='copilot_cache')
    op.drop_table('copilot_cache')
    op.drop_index(op.f('ix_activity_baselines_organization_id'), table_name='activity_baselines')
    op.drop_index(op.f('ix_activity_baselines_activity_type'), table_name='activity_baselines')
    op.drop_table('activity_baselines')
    op.drop_table('organizations')
    # ### end Alembic commands ###
